// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://kfceloxwzzsjtaajdefj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtmY2Vsb3h3enpzanRhYWpkZWZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ5MDU4OTEsImV4cCI6MjA5MDQ4MTg5MX0.Ki6m_rFpd8rYnYhFkPAOW1aWx7AIC5aeBnONLuy_6vw";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);