// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://dygcylhtdsixsubaaerc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR5Z2N5bGh0ZHNpeHN1YmFhZXJjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM4MDc2MzcsImV4cCI6MjA4OTM4MzYzN30.deNZggsVX6C3-CxFdtNiRKit1RnzqLr53yhQTMfPTYc";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);